### ISSUE TITLE
getRangeSetting should change range array accorantly

### ISSUE THREAD

**Issue by lestofante** [jenschr/Arduino-libraries#1]
the funciotn void ADXL345::getRangeSetting(byte\* rangeSetting)

should change the gain array discordantly, so the result will always be in G. 

just multiply the  gain by the (new range / old range) and remember that the first reading probably still use the old gain if in continuous mode

**Comment by jenschr** [comment]
Sorry for not replying earlier, but I didn't get an alert on this from GIT back in 2012 when you posted :-/

I'm not sure changing the gain values automatically is correct? Please explain?
